#Mount Drive 

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
from matplotlib import pyplot as plt
from sklearn.utils import shuffle
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score, classification_report
import numpy as np
import pandas as pd
import os, sys
import cv2
import re
path = "/content/drive/MyDrive/image.orig"
dirs = os.listdir(path)

#Creat Grey-Scaled Histogram of images and Creat Dataset in csv file

In [3]:
my_list = []
for filename in dirs:
        img = cv2.imread(os.path.join(path,filename), cv2.COLOR_BGR2RGB)
        image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        hist = cv2.calcHist([image], [0], None, [256], [0, 256])
        #to normalize data 
        hist /= hist.sum()
        hist = hist.flatten()
        my_list.append(hist)
data = np.array(my_list)
print(data)
df = pd.DataFrame(data)
df.to_csv('data.csv')

[[1.0172526e-05 5.0862629e-05 5.0862629e-05 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [8.1380211e-05 8.5449219e-04 1.1189779e-03 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 5.0862629e-05 8.1380211e-05 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 ...
 [6.1035156e-05 1.5258789e-04 2.9500326e-04 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 1.4241536e-04 1.7293294e-04 ... 4.0690105e-05
  4.0690105e-05 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0172526e-05
  3.0517578e-05 0.0000000e+00]]


#Upload Created csv file

In [4]:
dataframe = pd.read_csv("/content/drive/MyDrive/ankit_data.csv")

In [5]:
#shape of dataset
print(dataframe.shape)

(1000, 257)


In [6]:
'''To know the format of csv'''
dataframe.head(2)

Image_name    0        1         2         3  ...  251  252  253  254  255
0    132.jpg  0.0  0.00001  0.000102  0.000092  ...  0.0  0.0  0.0  0.0  0.0
1    158.jpg  0.0  0.00002  0.000010  0.000000  ...  0.0  0.0  0.0  0.0  0.0

[2 rows x 257 columns]

#To Drop Extra Column of Image_name

In [7]:
name = []
name = dataframe['Image_name'] 
dataframe = dataframe.drop('Image_name', axis = 1)

#Creat RGB Histogram of dataset

In [8]:
blue, green, red = [], [], []
my_list = []
counter = 0 
for filename in dirs:
  temp = []
  counter = counter + 1
  img = cv2.imread(os.path.join(path,filename),cv2.COLOR_BGR2RGB)
  chans = cv2.split(img)
  colors = ("b", "g", "r")
  i = 0
  # loop over the image channels
  for (chan, color) in zip(chans, colors):
    # create a histogram for the current channel and plot it
    hist = cv2.calcHist([chan], [0], None, [256], [0, 256])
    hist /= hist.sum()
    hist = hist.flatten()
    hist = list(hist)
    temp = temp + hist
  temp = np.array(temp)
  my_list.append(temp)
my_list = np.array(my_list)
df = pd.DataFrame(my_list)
#RGB data in single 1-D so (256*3) column and 1000 pattern(row)
print(df)
df.to_csv('rgb.csv')

          0         1         2    ...       765       766       767
0    0.001017  0.000102  0.000122  ...  0.000000  0.000010  0.000000
1    0.008942  0.002991  0.003642  ...  0.000010  0.000000  0.000041
2    0.001404  0.000295  0.000326  ...  0.000020  0.000031  0.000092
3    0.000122  0.000010  0.000081  ...  0.000092  0.000071  0.000336
4    0.007558  0.002340  0.002248  ...  0.000000  0.000000  0.000000
..        ...       ...       ...  ...       ...       ...       ...
995  0.001282  0.000214  0.000285  ...  0.000000  0.000000  0.000010
996  0.023865  0.003031  0.003825  ...  0.000621  0.000519  0.003998
997  0.034698  0.006388  0.007273  ...  0.000031  0.000020  0.000031
998  0.054159  0.008046  0.009094  ...  0.000163  0.000183  0.001027
999  0.001770  0.001292  0.001943  ...  0.000000  0.000010  0.000051

[1000 rows x 768 columns]


#label the data according to class 
i.e. (0-99) -> [1] class


In [9]:
''' store in label list'''
name = list(name)
label = []
for i in range(0, len(name)):
  temp = list(map(int, re.findall(r'\d+', name[i])))
  label.append(temp)
label = np.array(label)
label = label.flatten()

In [10]:

for i in range(0, label.shape[0]):
  if(label[i]<100):
    label[i] = 1
  if(label[i]<=199 and label[i]>=100):
    label[i] = 2
  if(label[i]<=299 and label[i]>=200):
    label[i] = 3
  if(label[i]<=399 and label[i]>=300):
    label[i] = 4
  if(label[i]<=499 and label[i]>=400):
    label[i] = 5
  if(label[i]<=599 and label[i]>=500):
    label[i] = 6
  if(label[i]<=699 and label[i]>=600):
    label[i] = 7
  if(label[i]<=799 and label[i]>=700):
    label[i] = 8
  if(label[i]<=899 and label[i]>=800):
    label[i] = 9
  if(label[i]<=999 and label[i]>=900):
    label[i] = 10

#K-Fold for 5 fold

In [11]:
X = np.array(df)
y = label

In [12]:
X, y = shuffle(X, y, random_state=100)

In [13]:
def fold(features,y_actual):
  kf = KFold(n_splits=5,random_state=1000, shuffle=True)
  kf.get_n_splits(features)
  all_x_train = []
  all_x_test = []
  all_y_train = []
  all_y_test = []
  for train_index, test_index in kf.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = y_actual[train_index], y_actual[test_index]
    all_x_train.append(X_train)
    all_x_test.append(X_test)
    all_y_train.append(y_train)
    all_y_test.append(y_test)
  all_x_train, all_x_test, all_y_train, all_y_test  = np.array(all_x_train), np.array(all_x_test), np.array(all_y_train), np.array(all_y_test)
  for i in range(0, 5):
    all_y_train[i] = all_y_train[i].flatten()
  return all_x_train, all_x_test, all_y_train, all_y_test

In [14]:
all_x_train, all_x_test, all_y_train, all_y_test = fold(X, y)

#Hyperparameter Tuning 

In [15]:
"""
Creating the validation set to get the best hyperparameter.training and validation into an 80:20 ratio.
"""
from sklearn.linear_model import SGDClassifier        #Import Stocastic Gradient Descent
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
X_train, X_validation, y_train, y_validation = train_test_split(all_x_train[0], all_y_train[0], test_size=0.20, random_state=42)

In [16]:
# hyperparameter tuning for logistic accuracy
def logistic_hyperparameter_tuning(epoch, alpha, roh, n_iter_no_change, X_train, X_validation, y_train, y_validation):
  val_acc = []
  for i in range(0, epoch.shape[0]):
    # we are taking logloss function for error calculation
    logistic_reg_classifier = OneVsRestClassifier(SGDClassifier(loss = 'log', alpha = alpha[i], fit_intercept = True, max_iter = epoch[i], tol = roh[i], n_iter_no_change = n_iter_no_change[i])).fit(X_train, y_train)
    predicted = logistic_reg_classifier.predict(X_validation)
    val_acc.append(accuracy_score(y_validation, predicted)*100)
  # Get the maximum accuracy on validation
  max_value = max(val_acc)
  max_index = val_acc.index(max_value)
  best_hyperparameter = (epoch[max_index], alpha[max_index], roh[max_index], n_iter_no_change[max_index])
  print("Best Hyperparameter:")
  print("Epoch = ", epoch[max_index])
  print("Alpha = ", alpha[max_index])
  print("Roh = ", roh[max_index])
  print("n_iter_no_change (Number of iterations with no improvement) = ", n_iter_no_change[max_index])
  return best_hyperparameter

**Set parameter for Best Hyperparameter**

In [17]:
epoch = np.array([100, 150, 200, 250, 300, 350, 400, 450, 500, 550])
alpha = np.array([0.01, 0.001, 0.0001, 0.00001, 0.125, 0.0125, 0.00125, 0.15, 0.25, 0.3])
roh = np.array([0.00001, 0.00001, 0.000001, 0.0000001, 0.000001, 0.0001, 0.0001, 0.0001, 0.0001, 0.000001])
n_iter_no_change = np.array([8, 9, 10, 11, 12, 13, 14, 15, 16, 18])
epoch, alpha, roh, n_iter_no_change = logistic_hyperparameter_tuning(epoch, alpha, roh, n_iter_no_change, X_train, X_validation, y_train, y_validation)

Best Hyperparameter:
Epoch =  250
Alpha =  1e-05
Roh =  1e-07
n_iter_no_change (Number of iterations with no improvement) =  11


#Overfitting checking in Logistic_Regression

In [18]:
logistic_regression = OneVsRestClassifier(SGDClassifier(loss = 'log', alpha = alpha, fit_intercept = True, max_iter = epoch, tol = roh, n_iter_no_change = n_iter_no_change))
logistic_regression.fit(X_train, y_train)
print("Accuracy on training data: " + str(logistic_regression.score(X_train, y_train)*100) + "%")
test_predicted = logistic_regression.predict(all_x_test[0])
print("-"*100)
print("Testing Accuracy Score: " + str(accuracy_score(all_y_test[0], test_predicted)*100))
print("-"*100)
valid_predicted = logistic_regression.predict(X_validation)
print("Validation Accuracy Score: " + str(accuracy_score(y_validation, valid_predicted)*100))
print("-"*100)

Accuracy on training data: 42.03125%
----------------------------------------------------------------------------------------------------
Testing Accuracy Score: 34.0
----------------------------------------------------------------------------------------------------
Validation Accuracy Score: 28.749999999999996
----------------------------------------------------------------------------------------------------


#Logistic Regression K-fold wise

In [19]:
for i in range(0, 5): # for 5 fold
  print("For fold no:", i+1)
  print("-"*100)
  logistic_regression = OneVsRestClassifier(SGDClassifier(loss = 'log', alpha = 0.00001, fit_intercept = True, max_iter = epoch, tol = roh, n_iter_no_change = n_iter_no_change))
  logistic_regression.fit(X_train,y_train)
  print("Accuracy on training data: " + str(logistic_regression.score(all_x_train[i], all_y_train[i])*100) + "%")
  predicted = logistic_regression.predict(all_x_test[i])
  print("Testing Accuracy Score: " + str(accuracy_score(all_y_test[i], predicted)*100))
  valid_predicted = logistic_regression.predict(X_validation)
  print("Validation Accuracy Score: " + str(accuracy_score(y_validation, valid_predicted)*100))
  print("Confusion Matrix : \n" + str(confusion_matrix(all_y_test[i], predicted)))
  print("Classification Report for 10-classes: ")
  out_labels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  print(classification_report(all_y_test[i], predicted, out_labels, digits=4))
  print("-"*100)

For fold no: 1
----------------------------------------------------------------------------------------------------
Accuracy on training data: 44.5%
Testing Accuracy Score: 38.0
Validation Accuracy Score: 33.125
Confusion Matrix : 
[[ 2  3  2  0  3  0  1  2  5  1]
 [ 2 10  0  0  0  0  0  0  3  1]
 [ 3  0  7  0  0  0  0  1  3 10]
 [ 3  0  2  1 10  0  0  0  3  1]
 [ 2  0  1  0  5  0  0  1  1  2]
 [ 2  0  0  0  7  0  3  4  0  7]
 [ 0  1  1  0  1  0  8  3  4  8]
 [ 0  2  1  0  0  0  0 12  0  5]
 [ 0  1  1  0  0  0  0  0 17  2]
 [ 2  0  0  0  1  0  0  0  2 14]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1     0.1250    0.1053    0.1143        19
           2     0.5882    0.6250    0.6061        16
           3     0.4667    0.2917    0.3590        24
           4     1.0000    0.0500    0.0952        20
           5     0.1852    0.4167    0.2564        12
           6     0.0000    0.0000    0.0000        23
           7     0.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy on training data: 38.75%
Testing Accuracy Score: 39.5
Validation Accuracy Score: 29.375
Confusion Matrix : 
[[ 2  6  0  0  0  9  0  2  1  1]
 [ 0 17  0  0  0  3  1  0  1  0]
 [ 0 10  1  1  0  5  0  0  1  1]
 [ 0  2  0  7  4  3  0  0  0  0]
 [ 0  2  1  3  4 12  0  0  0  0]
 [ 1  3  0  0  0 18  0  1  0  0]
 [ 0  3  0  0  0  9  4  1  0  1]
 [ 0  3  0  0  0  4  0 11  0  0]
 [ 0 10  0  0  0  6  0  0  6  0]
 [ 0  3  0  1  0  6  0  0  0  9]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1     0.6667    0.0952    0.1667        21
           2     0.2881    0.7727    0.4198        22
           3     0.5000    0.0526    0.0952        19
           4     0.5833    0.4375    0.5000        16
           5     0.5000    0.1818    0.2667        22
           6     0.2400    0.7826    0.3673        23
           7     0.8000    0.2222    0.3478        18
           8     0.7333    0.6111    0.6667        18
           9     0.6667   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy on training data: 37.0%
Testing Accuracy Score: 47.0
Validation Accuracy Score: 28.125
Confusion Matrix : 
[[ 3  0  0  5  0  0  1  0  1  1]
 [ 0 12  0 12  0  0  0  0  4  0]
 [ 0  1  1 17  0  0  0  0  1  0]
 [ 0  0  0 21  4  0  0  0  0  0]
 [ 1  0  0 13 10  1  1  0  0  0]
 [ 0  0  0 10  0  2  3  3  0  0]
 [ 0  0  0  4  0  0  5  0  0  1]
 [ 0  0  0  4  0  0  0 19  0  1]
 [ 1  1  0  6  0  0  0  1 10  0]
 [ 0  0  0  8  0  0  0  0  0 11]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1     0.6000    0.2727    0.3750        11
           2     0.8571    0.4286    0.5714        28
           3     1.0000    0.0500    0.0952        20
           4     0.2100    0.8400    0.3360        25
           5     0.7143    0.3846    0.5000        26
           6     0.6667    0.1111    0.1905        18
           7     0.5000    0.5000    0.5000        10
           8     0.8261    0.7917    0.8085        24
           9     0.6250    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Single Layer Perceptron

In [20]:
from sklearn.datasets import load_digits
from sklearn.linear_model import Perceptron
X, y = load_digits(return_X_y=True)



#Overfitting for Single Layer Perceptron

In [21]:
slp = Perceptron(tol=roh, random_state = 0)
slp.fit(X_train, y_train)
print("Accuracy on training data: " + str(slp.score(X_train, y_train)*100) + "%")
test_predicted = slp.predict(all_x_test[0])
print("-"*100)
print("Testing Accuracy Score: " + str(accuracy_score(all_y_test[0], test_predicted)*100))
print("-"*100)
valid_predicted = slp.predict(X_validation)
print("Validation Accuracy Score: " + str(accuracy_score(y_validation, valid_predicted)*100))
print("-"*100)

Accuracy on training data: 32.34375%
----------------------------------------------------------------------------------------------------
Testing Accuracy Score: 24.5
----------------------------------------------------------------------------------------------------
Validation Accuracy Score: 25.624999999999996
----------------------------------------------------------------------------------------------------


#SLP K-fold wise

In [23]:
for i in range(0, 5): # for 5 fold
  print("For fold no:", i+1)
  print("-"*100)
  slp = Perceptron(tol=roh, random_state = 0)
  slp.fit(all_x_train[0], all_y_train[0])
  print("Accuracy on training data: " + str(slp.score(all_x_train[i], all_y_train[i])*100) + "%")
  predicted = slp.predict(all_x_test[i])
  print("Testing Accuracy Score: " + str(accuracy_score(all_y_test[i], predicted)*100))
  valid_predicted = slp.predict(X_validation)
  print("Validation Accuracy Score: " + str(accuracy_score(y_validation, valid_predicted)*100))
  print('Confusion Matrix : \n' + str(confusion_matrix(all_y_test[i], predicted)))
  print("Classification Report for 10-classes: ")
  out_labels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  print(classification_report(all_y_test[i], predicted, out_labels, digits=5))
  print("-"*100)

For fold no: 1
----------------------------------------------------------------------------------------------------
Accuracy on training data: 26.75%
Testing Accuracy Score: 19.5
Validation Accuracy Score: 28.749999999999996
Confusion Matrix : 
[[ 0  7  1  1  1  0  0  0  8  1]
 [ 0 15  0  0  0  0  0  0  1  0]
 [ 0 12  1  0  0  0  0  0 10  1]
 [ 0  5  0  2  8  0  0  0  5  0]
 [ 0  2  0  0  4  0  0  0  6  0]
 [ 0  6  0  1  5  0  4  0  7  0]
 [ 0 12  0  0  0  2  3  0  9  0]
 [ 0  7  0  0  0  0  0  0 12  1]
 [ 0 10  0  0  0  0  0  0 11  0]
 [ 0  9  0  0  0  1  0  0  6  3]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1    0.00000   0.00000   0.00000        19
           2    0.17647   0.93750   0.29703        16
           3    0.50000   0.04167   0.07692        24
           4    0.50000   0.10000   0.16667        20
           5    0.22222   0.33333   0.26667        12
           6    0.00000   0.00000   0.00000        23
      

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy on training data: 24.625%
Testing Accuracy Score: 28.000000000000004
Validation Accuracy Score: 28.749999999999996
Confusion Matrix : 
[[ 0  9  0  0  3  0  1  0  7  1]
 [ 0 19  0  0  0  0  0  0  3  0]
 [ 0 12  0  0  0  0  0  0  7  0]
 [ 0  5  0  4  3  0  0  0  4  0]
 [ 0  8  0  3  7  0  0  0  4  0]
 [ 0  9  0  0  2  3  3  0  6  0]
 [ 0  6  0  0  0  0  7  0  5  0]
 [ 0 12  0  0  0  0  1  0  5  0]
 [ 0 12  0  0  0  0  0  0 10  0]
 [ 0  9  0  0  0  0  0  0  4  6]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1    0.00000   0.00000   0.00000        21
           2    0.18812   0.86364   0.30894        22
           3    0.00000   0.00000   0.00000        19
           4    0.57143   0.25000   0.34783        16
           5    0.46667   0.31818   0.37838        22
           6    1.00000   0.13043   0.23077        23
           7    0.58333   0.38889   0.46667        18
           8    0.00000   0.00000   0.00000        18

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy on training data: 24.25%
Testing Accuracy Score: 29.5
Validation Accuracy Score: 28.749999999999996
Confusion Matrix : 
[[ 0  8  0  0  1  0  0  0  1  1]
 [ 0 24  0  0  0  0  0  0  4  0]
 [ 0 12  0  0  0  0  0  0  8  0]
 [ 0  8  0  1  8  0  0  0  8  0]
 [ 0  7  0  3  9  0  0  0  7  0]
 [ 0  6  0  1  0  2  2  0  7  0]
 [ 0  4  0  0  0  0  4  0  2  0]
 [ 0 14  0  0  0  0  0  0 10  0]
 [ 0  7  0  0  0  0  0  0 12  0]
 [ 0  9  0  0  0  0  0  0  3  7]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1    0.00000   0.00000   0.00000        11
           2    0.24242   0.85714   0.37795        28
           3    0.00000   0.00000   0.00000        20
           4    0.20000   0.04000   0.06667        25
           5    0.50000   0.34615   0.40909        26
           6    1.00000   0.11111   0.20000        18
           7    0.66667   0.40000   0.50000        10
           8    0.00000   0.00000   0.00000        24
           9  

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Sigmoid Neuron

In [24]:
import numpy as np
import matplotlib.pyplot as plt
# it's slp
class SigmoidNeuron:
    def __init__(self, epoch = 10, roh=1e-3):
        self.epoch = epoch
        self.roh = roh

    def predict(self, X):
        return self.predict_(self.add_bias(X))
    
    def predict_(self, X):
        pre_vals = np.dot(X, self.weights.T).reshape(-1,len(self.classes))
        return self.softmax(pre_vals)
    
    def softmax(self, z):
        return np.exp(z) / np.sum(np.exp(z), axis=1).reshape(-1,1)

    def predict_classes(self, X):
        self.probs_ = self.predict(X)
        return np.vectorize(lambda c: self.classes[c])(np.argmax(self.probs_, axis=1))
  
    def add_bias(self, X):
        return np.insert(X, 0, 1, axis=1)

    def one_hot(self, y):
        return np.eye(len(self.classes))[np.vectorize(lambda c: self.class_labels[c])(y).reshape(-1)]
    
    def score(self, X, y):
        return np.mean(self.predict_classes(X) == y)
    
    def evaluate_(self, X, y):
        return np.mean(np.argmax(self.predict_(X), axis=1) == np.argmax(y, axis=1))

    def logloss(self, y, probs):
        return np.mean(-y*np.log(probs) - (1-y)*np.log(1-probs))

    def cross_entropy(self, y, probs):
        return -1 * np.mean(y * np.log(probs))

    def mse(self, y, probs):
        return (((y - probs)**2).mean())/2
        
    def fit(self, X, y, lr=0.1, rand_seed=4, verbose=False):
        np.random.seed(rand_seed) 
        self.classes = np.unique(y)
        self.class_labels = {c:i for i,c in enumerate(self.classes)}
        X = self.add_bias(X)
        y = self.one_hot(y)
        self.loss = []
        self.weights = np.zeros(shape=(len(self.classes),X.shape[1]))*0.1
        self.fit_data(X, y, lr, verbose)
        return self
 
    def fit_data(self, X, y, lr, verbose):
        i = 0
        xt, yt = all_x_test[0], all_y_test[0]
        xtr, ytr = all_x_train[0], all_y_train[0]
        while (not self.epoch or i < self.epoch):
            self.loss.append(self.mse(y, self.predict_(X)))
            error = y - self.predict_(X)
            update = (lr * np.dot(error.T, X))
            self.weights += update
            if np.abs(update).max() < self.roh: break
            i +=1

In [27]:
for i in range(0, 5): # for 5 fold
  print("For fold no:", i+1)
  print("-"*100)
  sgn = SigmoidNeuron(roh=1e-5)
  sgn.fit(all_x_train[0], all_y_train[0], lr=0.01)
  print("Accuracy on training data: " + str(sgn.score(all_x_train[i], all_y_train[i])*100) + "%")
  predicted = sgn.predict_classes(all_x_test[i])
  print("Testing Accuracy Score: " + str(accuracy_score(all_y_test[i], predicted)*100))
  valid_predicted = sgn.predict_classes(X_validation)
  print("Validation Accuracy Score: " + str(accuracy_score(y_validation, valid_predicted)*100))
  print('Confusion Matrix : \n' + str(confusion_matrix(all_y_test[i], predicted)))
  print("Classification Report for 10-classes: ")
  out_labels = [1,2, 3, 4, 5, 6, 7, 8, 9, 10]
  print(classification_report(all_y_test[i], predicted, out_labels, digits=5))
  print("-"*100)

For fold no: 1
----------------------------------------------------------------------------------------------------
Accuracy on training data: 19.625%
Testing Accuracy Score: 15.5
Validation Accuracy Score: 20.625
Confusion Matrix : 
[[ 0 12  0  0  4  0  0  0  0  3]
 [ 0 16  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  2  0  0  0  0  4]
 [ 0 10  0  0 10  0  0  0  0  0]
 [ 0  6  0  0  6  0  0  0  0  0]
 [ 0 10  0  0  8  0  2  0  0  3]
 [ 0 16  0  0  3  0  3  0  0  4]
 [ 0 17  0  0  1  0  0  0  0  2]
 [ 0 20  0  0  1  0  0  0  0  0]
 [ 0 12  0  0  1  0  0  0  0  6]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1    0.00000   0.00000   0.00000        19
           2    0.11679   1.00000   0.20915        16
           3    0.00000   0.00000   0.00000        24
           4    0.00000   0.00000   0.00000        20
           5    0.16667   0.50000   0.25000        12
           6    0.00000   0.00000   0.00000        23
           7    0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           1    0.00000   0.00000   0.00000        28
           2    0.11842   1.00000   0.21176        18
           3    0.00000   0.00000   0.00000        21
           4    0.00000   0.00000   0.00000        22
           5    0.38462   0.62500   0.47619        16
           6    0.00000   0.00000   0.00000        18
           7    1.00000   0.10000   0.18182        20
           8    0.00000   0.00000   0.00000        18
           9    0.00000   0.00000   0.00000        18
          10    0.35000   0.33333   0.34146        21

    accuracy                        0.18500       200
   macro avg    0.18530   0.20583   0.12112       200
weighted avg    0.17818   0.18500   0.11119       200

----------------------------------------------------------------------------------------------------
For fold no: 4
----------------------------------------------------------------------------------------------------
Accuracy on training dat

#Multilayer Perceptron

In [ ]:
from sklearn.neural_network import MLPClassifier

#Overfitting for Multilayer Perceptron

In [ ]:
mlp = mlp = MLPClassifier(hidden_layer_sizes=(258), activation='logistic',solver='sgd', random_state=1, max_iter=1000).fit(all_x_train[0], all_y_train[0])
mlp.fit(X_train, y_train)
print("Accuracy on training data: " + str(mlp.score(X_train, y_train)*100) + "%")
test_predicted = mlp.predict(all_x_test[0])
print("-"*100)
print("Testing Accuracy Score: " + str(accuracy_score(all_y_test[0], test_predicted)*100))
print("-"*100)
valid_predicted = mlp.predict(X_validation)
print("Validation Accuracy Score: " + str(accuracy_score(y_validation, valid_predicted)*100))
print("-"*100)

Accuracy on training data: 10.9375%
----------------------------------------------------------------------------------------------------
Testing Accuracy Score: 10.0
----------------------------------------------------------------------------------------------------
Validation Accuracy Score: 6.25
----------------------------------------------------------------------------------------------------


In [ ]:
for i in range(0, 5): # for 5 fold
  print("For fold no:", i+1)
  print("-"*100)
  mlp = MLPClassifier(hidden_layer_sizes=(258), activation='logistic',solver='sgd', random_state=1, max_iter=1000).fit(all_x_train[0], all_y_train[0])
  mlp.predict(all_x_train[0])
  print("Accuracy on training data: " + str(mlp.score(all_x_train[i], all_y_train[i])*100) + "%")
  predicted = mlp.predict(all_x_test[i])
  print("Testing Accuracy Score: " + str(accuracy_score(all_y_test[i], predicted)*100))
  valid_predicted = mlp.predict(X_validation)
  print("Validation Accuracy Score: " + str(accuracy_score(y_validation, valid_predicted)*100))
  print('Confusion Matrix : \n' + str(confusion_matrix(all_y_test[i], predicted)))
  print("Classification Report for 10-classes: ")
  out_labels = [1,2,3,4,5,6, 7, 8, 9, 10]
  print(classification_report(all_y_test[i], predicted, out_labels, digits=5))
  print("-"*100)

For fold no: 1
----------------------------------------------------------------------------------------------------
Accuracy on training data: 11.0%
Testing Accuracy Score: 6.0
Validation Accuracy Score: 9.375
Confusion Matrix : 
[[12  0  0  0  0  0  0  0  0  0]
 [23  0  0  0  0  0  0  0  0  0]
 [27  0  0  0  0  0  0  0  0  0]
 [21  0  0  0  0  0  0  0  0  0]
 [15  0  0  0  0  0  0  0  0  0]
 [23  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [19  0  0  0  0  0  0  0  0  0]
 [21  0  0  0  0  0  0  0  0  0]
 [19  0  0  0  0  0  0  0  0  0]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1    0.06000   1.00000   0.11321        12
           2    0.00000   0.00000   0.00000        23
           3    0.00000   0.00000   0.00000        27
           4    0.00000   0.00000   0.00000        21
           5    0.00000   0.00000   0.00000        15
           6    0.00000   0.00000   0.00000        23
           7    0.000

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy on training data: 9.625%
Testing Accuracy Score: 11.5
Validation Accuracy Score: 9.375
Confusion Matrix : 
[[23  0  0  0  0  0  0  0  0  0]
 [23  0  0  0  0  0  0  0  0  0]
 [22  0  0  0  0  0  0  0  0  0]
 [19  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [16  0  0  0  0  0  0  0  0  0]
 [18  0  0  0  0  0  0  0  0  0]
 [19  0  0  0  0  0  0  0  0  0]
 [19  0  0  0  0  0  0  0  0  0]
 [21  0  0  0  0  0  0  0  0  0]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1    0.11500   1.00000   0.20628        23
           2    0.00000   0.00000   0.00000        23
           3    0.00000   0.00000   0.00000        22
           4    0.00000   0.00000   0.00000        19
           5    0.00000   0.00000   0.00000        20
           6    0.00000   0.00000   0.00000        16
           7    0.00000   0.00000   0.00000        18
           8    0.00000   0.00000   0.00000        19
           9    0.00000   0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy on training data: 9.75%
Testing Accuracy Score: 11.0
Validation Accuracy Score: 9.375
Confusion Matrix : 
[[22  0  0  0  0  0  0  0  0  0]
 [23  0  0  0  0  0  0  0  0  0]
 [16  0  0  0  0  0  0  0  0  0]
 [18  0  0  0  0  0  0  0  0  0]
 [24  0  0  0  0  0  0  0  0  0]
 [22  0  0  0  0  0  0  0  0  0]
 [11  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [26  0  0  0  0  0  0  0  0  0]
 [18  0  0  0  0  0  0  0  0  0]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1    0.11000   1.00000   0.19820        22
           2    0.00000   0.00000   0.00000        23
           3    0.00000   0.00000   0.00000        16
           4    0.00000   0.00000   0.00000        18
           5    0.00000   0.00000   0.00000        24
           6    0.00000   0.00000   0.00000        22
           7    0.00000   0.00000   0.00000        11
           8    0.00000   0.00000   0.00000        20
           9    0.00000   0.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy on training data: 9.25%
Testing Accuracy Score: 13.0
Validation Accuracy Score: 9.375
Confusion Matrix : 
[[26  0  0  0  0  0  0  0  0  0]
 [18  0  0  0  0  0  0  0  0  0]
 [15  0  0  0  0  0  0  0  0  0]
 [17  0  0  0  0  0  0  0  0  0]
 [24  0  0  0  0  0  0  0  0  0]
 [18  0  0  0  0  0  0  0  0  0]
 [28  0  0  0  0  0  0  0  0  0]
 [15  0  0  0  0  0  0  0  0  0]
 [14  0  0  0  0  0  0  0  0  0]
 [25  0  0  0  0  0  0  0  0  0]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1    0.13000   1.00000   0.23009        26
           2    0.00000   0.00000   0.00000        18
           3    0.00000   0.00000   0.00000        15
           4    0.00000   0.00000   0.00000        17
           5    0.00000   0.00000   0.00000        24
           6    0.00000   0.00000   0.00000        18
           7    0.00000   0.00000   0.00000        28
           8    0.00000   0.00000   0.00000        15
           9    0.00000   0.

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy on training data: 10.375%
Testing Accuracy Score: 8.5
Validation Accuracy Score: 9.375
Confusion Matrix : 
[[17  0  0  0  0  0  0  0  0  0]
 [13  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [25  0  0  0  0  0  0  0  0  0]
 [17  0  0  0  0  0  0  0  0  0]
 [21  0  0  0  0  0  0  0  0  0]
 [23  0  0  0  0  0  0  0  0  0]
 [27  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [17  0  0  0  0  0  0  0  0  0]]
Classification Report for 10-classes: 
              precision    recall  f1-score   support

           1    0.08500   1.00000   0.15668        17
           2    0.00000   0.00000   0.00000        13
           3    0.00000   0.00000   0.00000        20
           4    0.00000   0.00000   0.00000        25
           5    0.00000   0.00000   0.00000        17
           6    0.00000   0.00000   0.00000        21
           7    0.00000   0.00000   0.00000        23
           8    0.00000   0.00000   0.00000        27
           9    0.00000   0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
